// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzlhypju1k2SfbZQaCVWsFbNyswA136s',
    appId: '1:59843519787:web:27d897268290618308d16e',
    messagingSenderId: '59843519787',
    projectId: 'e-book-store-46206',
    authDomain: 'e-book-store-46206.firebaseapp.com',
    storageBucket: 'e-book-store-46206.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTKXbSQRIzef0PpeJr9nrwEHVmCZnQufA',
    appId: '1:59843519787:android:9ea1b1036834358308d16e',
    messagingSenderId: '59843519787',
    projectId: 'e-book-store-46206',
    storageBucket: 'e-book-store-46206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLpJZkx5jaBc22c86iGqL35IytCH4KW4',
    appId: '1:59843519787:ios:9e18cf996b11a2e608d16e',
    messagingSenderId: '59843519787',
    projectId: 'e-book-store-46206',
    storageBucket: 'e-book-store-46206.appspot.com',
    iosClientId: '59843519787-9tnngo2q90inae6vd7cv2u3pghepo4mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLpJZkx5jaBc22c86iGqL35IytCH4KW4',
    appId: '1:59843519787:ios:9e18cf996b11a2e608d16e',
    messagingSenderId: '59843519787',
    projectId: 'e-book-store-46206',
    storageBucket: 'e-book-store-46206.appspot.com',
    iosClientId: '59843519787-9tnngo2q90inae6vd7cv2u3pghepo4mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzlhypju1k2SfbZQaCVWsFbNyswA136s',
    appId: '1:59843519787:web:498074c5010207e708d16e',
    messagingSenderId: '59843519787',
    projectId: 'e-book-store-46206',
    authDomain: 'e-book-store-46206.firebaseapp.com',
    storageBucket: 'e-book-store-46206.appspot.com',
  );

}